include ../../common.make
include $(GNUSTEP_MAKEFILES)/common.make

PACKAGE_NAME="GDL2Intro"
DOCUMENT_NAME=GDL2Intro

GDL2Intro_TEXI_FILES=GDL2Intro.texi

include $(GNUSTEP_MAKEFILES)/documentation.make

