include $(GNUSTEP_MAKEFILES)/common.make
include $(GNUSTEP_MAKEFILES)/Auxiliary/gdl2.make

include GNUmakefile.eoexample
include GNUmakefile.connection
include GNUmakefile.eoexample2

include $(GNUSTEP_MAKEFILES)/tool.make
