include $(GNUSTEP_MAKEFILES)/common.make
SUBPROJECT_NAME=Inspectors
ADDITIONAL_INCLUDE_DIRS+=-I../../

Inspectors_HAS_RESOURCE_BUNDLE=yes

Inspectors_RESOURCE_FILES=RelationshipInspector.gorm
Inspectors_OBJC_FILES=RelationshipInspector.m

Inspectors_RESOURCE_FILES+=AttributeInspector.gorm
Inspectors_OBJC_FILES+=AttributeInspector.m

include $(GNUSTEP_MAKEFILES)/subproject.make
